### ISSUE TITLE
Environment variables not supported and cause sync to error

### ISSUE THREAD

**Issue by jantari** [mgholam/TorpedoSync#3]
Hi, thanks for the great software first of all.

I created a test setup where I wanted to 2-way sync files between 2 Windows 10 VMs.

On the "server"-VM (Name in screenshot: win10) I created a share:
```
Unique Name: torpedo-share
Local Path: C:\torpedo-share
```

On the Client-VM (Name in screenshot: second win10), I created a connection:
```
Token: [RW-Token]
Local Path: %USERPROFILE%\torpedoshare-sync
```

The connection worked, however:

1. Instead of creating a folder `C:\Users\username\torpedoshare-sync` on the client-vm, it created a folder literally called `%USERPROFILE%` inside the torpedoshare program directory (so it treated it like a relative path)
2. A file then successfully synced from the server to the client into the literal `C:\Users\username\Downloads\TorpedoSync_exe.v.1.7.0\%USERPROFILE%\torpedoshare-sync` directory
3. After changing that file on the client side and waiting for the changes to sync to the server-side,
I saw errors appear in the console on the server side and the change(s) would never sync to it

My bug report boils down to the following:

Please support the use of environment variables in the "Local Path" entries, by use of [Environment.ExpandEnvironmentVariables()](https://docs.microsoft.com/dotnet/api/system.environment.expandenvironmentvariables?view=netcore-3.1)

Thanks!

EDIT: Forgot my screenshot, oops:
![Screenshot from 2020-02-13 22 26 47](https://user-images.githubusercontent.com/25607767/74587377-099a2b80-4ff2-11ea-88b3-e32c6b62f529.png)

**Comment by mgholam** [comment]
Thanks!
I will see what I can do.

**Comment by jantari** [comment]
I am not great at C# sadly, but from grep-ing through the source code with `find ./TorpedoSync/ -type f -exec grep -i "SyncFile" {} +;` it seems to me like both the Client and Server create `SyncFile` objects locally.

In that case, would it be enough to add a constructor to the `SyncFile` class inside [Entities.cs](https://github.com/mgholam/TorpedoSync/blob/master/TorpedoSync/Entities.cs) that calls `Environment.ExpandEnvironmentVariables()` on the `F`-parameter before creating the object?

**Comment by mgholam** [comment]
Check out v1.7.5
