### ISSUE TITLE
File Size is Limited to 2 GB?

### ISSUE THREAD

**Issue by ozz-project** [mgholam/TorpedoSync#5]
It seems that you cannot transfer files larger than 2 GB.
In this case the log shows this message

    07:30:25|INFO| null data : [FILENAME]!torpedosync
    07:30:25|INFO| original data size : 10.327
    07:30:25|INFO| compressed size : 686
    07:30:32|INFO| List of currently connected machines :
    07:30:32|INFO|   Connected to : 192.xxxxxxxx
    07:31:10|INFO| GC.......
    07:31:10|INFO|   GC Collection 0 = 747
    07:31:10|INFO|   GC Collection 1 = 684
    07:31:10|INFO|   GC Collection 2 = 672

After that the client is dead.  It still shows the connected clients, but does not accept any data.
After a restart of the service, the download of the data starts again.

**Comment by mgholam** [comment]
Thanks! 
I will look into it.
(side note: how are you using TS? and why such large files?)

**Comment by ozz-project** [comment]
i run TS as windows service.
I remember that the original ZIP implentation had a size limit. This was 2 GB. So I guess the zipstorer is the cause of the error.
(side note: i working with databases.... they always large) ;-)

**Comment by mgholam** [comment]
zip is only used for small files.

**Comment by mgholam** [comment]
Looking at the code, the offset into files in a `long` and TS only sends chunks of 10mb (default value) at a time so the problem is not the size limit.
It could be TS cannot open or read the file that is in use.

**Comment by ozz-project** [comment]
I can rule out the file being in use. These are manual backups.
It is noticeable that it always terminates at the same point.The copied file is always 2 GB in size.
I'll try some other files and different sizes.

**Comment by ozz-project** [comment]
I have created some fake files in different sizes.
i could successfully transfer files up to 10 GB (i did not create larger ones). So there is no problem with the file size.
Unfortunately the transfer of special files stops in the middle of the transfer. Reproducible. 
Also, I could not transfer files that I have already successfully transferred the second time. Again the same error.
`19:36:47|INFO| null data : d:\mysqlBackups\TorpedoSync\Backups\Fozzie\workspace\test files\1GB.txt.!torpedosync`

In the last case I deleted the file in the source and then copied it back. That made it work again.

Any idea what might be causing it?
Can I activate an additional log function?

**Comment by mgholam** [comment]
Try adding a log to `ClientCommands.cs` at line 115 method `Download`:
```c#
catch (Exception ex) { _log.Error(ex); }
```

**Comment by ozz-project** [comment]
I have done it. The error is below.  then the server restarted
`2020-05-21 18:11:29|ERROR|10|TorpedoSync.CoreWebServer|| System.Net.HttpListenerException (0x80004005): Zugriff verweigert
   bei System.Net.HttpListener.AddAllPrefixes()
   bei System.Net.HttpListener.Start()
   bei TorpedoSync.CoreWebServer.Start()
2020-05-21 18:12:40|DEBUG|1|TorpedoSync.TorpedoSyncServer|| Starting Server...
`

**Comment by mgholam** [comment]
Try increasing the sleep time on line 326 in method `GetServerIP`
```c#
public static ServerAddress GetServerIP(string name)
{
    var retry = 0;
    ServerAddress i = null;
    while (i == null && retry < 5)
    {
        i = ServerList.Find(x => x.Name == name);
        if (i == null)
        {
            System.Threading.Thread.Sleep(1000); // 100 -> 1000
            retry++;
        }
    }
    return i;
}
```

**Comment by mgholam** [comment]
also try :
```c#
...
   lock(_lock)
      i= ServerList.Find(x => x.Name == name);
...
```

**Comment by ozz-project** [comment]
> 
> 
> also try :
> 
> ```cs
> ...
>    lock(_lock)
>       i= ServerList.Find(x => x.Name == name);
> ...
> ```

I'm sorry. I couldn't find this place

The frist fix is installed and running now.
Just before your anwser i got a second error
´2020-05-22 09:10:11|ERROR|20|TorpedoSync.ServerCommands|| System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei TorpedoSync.ClientCommands.Download(Connection share, SyncFile file, Int64 start, Int32 size)
`

**Comment by mgholam** [comment]
add a lock to the `GetServerIP()` method in the code above.

**Comment by ozz-project** [comment]
I integrated both changes.
There is no additional entry in the log.
Only the known one.
`
19:24:18|INFO| null data : d:\mysqlBackups\.......!torpedosync
`

**Comment by mgholam** [comment]
Hmmm... then the failure is in the tcp send/receive, I will add retry logic for it.

**Comment by mgholam** [comment]
Get the new code from the repo, and let me know how it goes.

**Comment by ozz-project** [comment]
now it was running through.
I just have this error.

`2020-05-23 00:14:19|ERROR|14|TorpedoSync.ServerCommands|| System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei TorpedoSync.ClientCommands.Download(Connection share, SyncFile file, Int64 start, Int32 size)
`

**Comment by mgholam** [comment]
The log is from the `Download` method we first edited.

All else is fine, yes?

**Comment by ozz-project** [comment]
it would seem so.
MD5 Checks fine as well.
