### ISSUE TITLE
" Token not found on connected machine"

### ISSUE THREAD

**Issue by ozz-project** [mgholam/TorpedoSync#8]
I currently have the problem that I can not create a new connection. 
The error is always " Token not found on connected machine".

**Setup**
192.168.178.75
192.168.178.28

i want to copy data from x.75 to x.28
On .x.75 I have created a "Share" and want to include in x.25 under Connections.

In the log of 192.168.178.75
07:40:16|DEBUG| my ip = 192.168.178.75
07:40:18|INFO| List of currently connected machines :
07:40:18|INFO| Connected to : 192.168.178.28

In the log of 192.168.178.28
I do not find any info

I have already deleted the complete configuration (on all machines) and tried again. Still the same

**Comment by mgholam** [comment]
On `x.25` create a new connection and use the `read-only` or `read-write` guid from `x.75` for the share you want.

**Comment by ozz-project** [comment]
Yes, that's exactly what I did and that's where I got the error.
I have just repeated it again.

**Comment by mgholam** [comment]
Is `.75` your master? 

Also your logs say `.28` not `.25`

**Comment by ozz-project** [comment]
my mistake, x.28 is correct instead of x.25. Typo. i fixed it.
Yes x.75 is the master

**Comment by ozz-project** [comment]
`settings.config file on .75?`
{
   "UDPPort" : 21000,
   "TCPPort" : 21001,
   "WebPort" : 88,
   "LocalOnlyWeb" : true,
   "Shares" : [
      {
         "Path" : "d:\\Backups\\",
         "Name" : "Fozzie Backups",
         "ReadOnlyToken" : "19892A91-6C99-48B6-8CBA-F4031D6F8562",
         "ReadWriteToken" : "44A5B4AC-CAB3-452E-815B-8FB1662E6132"
      }
   ],
   "DownloadBlockSizeMB" : 10,
   "BatchZip" : true,
   "BatchZipFilesUnderMB" : 100,
   "SaveQueueEvery_X_Minute" : 1,
   "StartWebUI" : true,
   "NewSyncTimerSecs" : 120
}

on the `x.75` the folder `computers `is empty
also on the `x.28` the folder `computers `is empty

**Comment by ozz-project** [comment]
I tried it again..
no luck.

I have found something else. May this helps
When I run it as a service, the web interface comes up. I still can't create the connection. The error is still the same

When I start it from the command line, I get the following error and also the web interface does not come up.


```
 ______                     __     ____
/_  __/__  _______  ___ ___/ /__  / __/_ _____  ____
 / / / _ \/ __/ _ \/ -_) _  / _ \_\ \/ // / _ \/ __/
/_/  \___/_/ / .__/\__/\_,_/\___/___/\_, /_//_/\__/
            /_/                     /___/
-----------------------------------------------------
TorpedoSync - Folder Sync Application
Version      : 1.7.5.0
File Version : 1.7.6.676
-----------------------------------------------------
11:17:03|DEBUG| Starting Server...
11:17:03|DEBUG| UDP server on port = 21000
11:17:03|DEBUG| TCP server on port = 21001
11:17:03|DEBUG| WEB server on port = 88
11:17:03|DEBUG| my ip = 192.168.178.28
System.Net.Sockets.SocketException (0x80004005): Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat
   bei System.Net.Sockets.Socket.ReceiveFrom(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint& remoteEP)
   bei System.Net.Sockets.UdpClient.Receive(IPEndPoint& remoteEP)
   bei TorpedoSync.UDP.searchIP(Int32 port, IPAddress ip, List`1 list)


Press 'q' to exit...
11:17:05|ERROR| System.Net.HttpListenerException (0x80004005): Zugriff verweigert
   bei System.Net.HttpListener.AddAllPrefixes()
   bei System.Net.HttpListener.Start()
   bei TorpedoSync.CoreWebServer.Start()
```

**Comment by mgholam** [comment]
Make sure ports 21000, 21001 are open on your firewall for both machines.

**Comment by ozz-project** [comment]
according to netstat -ano, the ports are open or listening on both machines.

Active connections
  Proto Local address Remote address Status PID
  TCP 0.0.0.0:21001 0.0.0.0:0 ABH™REN 8504
  UDP 0.0.0.0:21000 *:* 8504

Active connections
  Proto Local address Remote address Status PID
  UDP 0.0.0.0:21000 *:* 8956
  TCP 0.0.0.0:21001 0.0.0.0:0 ABH™REN 8956

and that would not explain why the web gui works on the service but not on the command line.

**Comment by ozz-project** [comment]
I have. Windows has 2 different windows for the firewall.
I do not use the Defender firewall. I am using a different one. In the security center it says you are using a third party firewall and the Defender firewall is off.
When I open the Defender Firewall from the old system control, it says the opposite.
grrrrr

Sorry
